name: what if cron

on:
  schedule:
    - cron: '0 21 * * *'  # uruchamiaj codziennie o 08:00 UTC
  workflow_dispatch:     # umożliwia ręczne uruchomienie w panelu GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai requests

      - name: Run main.py
        run: python main.py
