name: What If Cron Job

on:
  schedule:
    - cron: '0 21 * * *'  # Codziennie o 21:00 UTC = 23:00 w Polsce
  workflow_dispatch:       # Pozwala też uruchomić ręcznie

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai>=1.3.8

      - name: Run main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          python main.py
