name: What If Cron Job

on:
  schedule:
    - cron: '0 21 * * *'  # codziennie o 21:00 UTC (23:00 w Polsce)
  workflow_dispatch:       # pozwala też uruchomić ręcznie z GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and reinstall OpenAI
        run: |
          pip install --upgrade pip
          pip uninstall -y openai
          pip install openai>=1.0.0

      - name: Run bot
        run: |
          python main.py
