name: what if cron

on:
  schedule:
    - cron: '0 21 * * *'  # 08:00 UTC = 10:00 czasu PL
  workflow_dispatch:     # pozwala ręcznie odpalić workflow z poziomu GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # pozwala na git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai requests

      - name: Run bot
        run: python main.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add scripts audio || true
          git commit -m "📦 auto: dodano skrypt i audio z $(date +'%Y-%m-%d')" || echo "Brak zmian do zapisania"
          git push
